use tabelas

drop database SIS_VOT;

create database SIS_VOT;

USE SIS_VOT;

create table TB_USUARIO (
	LOGIN VARCHAR(15) PRIMARY KEY,
	SENHA VARCHAR(15) NOT NULL,
	TIPO CHAR(1) NOT NULL,
	NOME VARCHAR(50) NULL,
	FL_TROCAR_SENHA CHAR(1) NOT NULL DEFAULT 'N'
)

INSERT INTO TB_USUARIO (LOGIN, SENHA, TIPO, NOME, FL_TROCAR_SENHA)
VALUES ('admin', 'admin', 'A', 'Administrador do Sistema', 'N')

--SELECT * FROM TB_USUARIO

create table TB_VOTACAO (
	ID_VOTACAO INT PRIMARY KEY,
	DESCRICAO VARCHAR(200) NOT NULL,
	DT_INI DATETIME NOT NULL,
	DT_FIM DATETIME NOT NULL,
	LOGIN_ADMIN VARCHAR(15) NULL 
		CONSTRAINT FK_USUARIO FOREIGN KEY 
			REFERENCES TB_USUARIO(LOGIN),
	FL_SECRETA CHAR(1) NOT NULL DEFAULT 'N'
)

INSERT INTO TB_VOTACAO (ID_VOTACAO, DESCRICAO, DT_INI, DT_FIM, LOGIN_ADMIN, FL_SECRETA)
VALUES (1, 'Prefeitura de São Paulo', '10-10-2010', '10-11-2010', 'admin', 'N')

--SELECT * FROM TB_VOTACAO

--drop table TB_CANDIDATO
create table TB_CANDIDATO (
	ID_CANDIDATO INT PRIMARY KEY,
	ID_VOTACAO INT NOT NULL,
	NOME VARCHAR(50) NOT NULL,
	IMAGEM VARBINARY(MAX) NULL,
	IMG_CONT_TYPE VARCHAR(30) NULL,
	DESCRICAO VARCHAR(200) NULL,
	NUMERO_VOTOS SMALLINT NOT NULL DEFAULT 0,
	
	CONSTRAINT FK_VOTACAO FOREIGN KEY (ID_VOTACAO)
		REFERENCES TB_VOTACAO(ID_VOTACAO)

)

--select * from TB_CANDIDATO

INSERT INTO TB_CANDIDATO (ID_VOTACAO, ID_CANDIDATO, NOME, IMAGEM, IMG_CONT_TYPE, DESCRICAO, NUMERO_VOTOS)
VALUES (1, 1, 'Macaco Simão', NULL, NULL, 'Macaco Prego da espécie Cebus apella', 0)


create table TB_ELEITORADO (
	LOGIN VARCHAR(15) NOT NULL,
	ID_VOTACAO INT NOT NULL,
	FL_COMPARECEU CHAR(1) NOT NULL DEFAULT 'N',
	ID_CANDIDATO_VOTADO INT NULL,
	
	CONSTRAINT PK_TB_ELEITORADO PRIMARY KEY (LOGIN, ID_VOTACAO),
	
	CONSTRAINT FK_CANDIDATO FOREIGN KEY (ID_CANDIDATO_VOTADO)
			REFERENCES TB_CANDIDATO(ID_CANDIDATO)

)